In [1]:
import os
import sys
import yaml
import pandas as pd

current_dir = os.path.dirname(os.path.abspath('.'))
project_root = os.path.abspath(os.path.join(current_dir, ".."))
sys.path.insert(0, project_root)

from functions.feature_selection import FeatureSelectionOrchestrator
from utils.plots import Pearson_correlation, Bar_plot

In [2]:
with open(os.path.join("../config/config.yaml"), "r") as f:
    config = yaml.safe_load(f)
        
with open(os.path.join( "../config/pipeline.yaml"), "r") as f:
    config_pipe = yaml.safe_load(f)

In [3]:
pipeline_name = "Pipeline3"

In [4]:
X_train = pd.read_parquet(fr'..\data\feature_eng\X_train_feat_eng_{pipeline_name}.parquet')
y_train = pd.read_parquet(fr'..\data\feature_eng\y_train_feat_eng_{pipeline_name}.parquet')

In [5]:
X_train.head()

,numerical_pipe_con__Age,numerical_pipe_con__Fare,numerical_pipe_dis__SibSp,numerical_pipe_dis__Parch,numerical_pipe_dis__IsAlone,numerical_pipe_dis__FamilySize,categorical_pipe__Pclass,categorical_pipe__Sex,categorical_pipe__Embarked,categorical_pipe__Title,categorical_pipe__Cabin_1p
331,1,1,0.0,0.0,1,0,2,0,0,0,4
733,1,0,0.0,0.0,1,0,1,0,0,0,1
382,1,0,0.0,0.0,1,0,0,0,0,0,1
704,1,0,1.0,0.0,0,0,0,0,0,0,1
813,0,1,4.0,2.0,0,1,0,1,0,3,1

In [6]:
feature_selection = FeatureSelectionOrchestrator()

In [7]:
Anova = feature_selection.apply(
        "Anova",
        X_train.filter(like='numerical_pipe_con'),
        y_train)

c:\Users\gustavo\anaconda3\envs\mf_tf\lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [8]:
mi = feature_selection.apply(
        "MutualInformationClassif", 
        X_train, 
        y_train)

c:\Users\gustavo\anaconda3\envs\mf_tf\lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [9]:
corr = feature_selection.apply(
        "PearsonCorrelation", 
        X_train.filter(like='numerical'), 
        y_train)

In [10]:
mi

categorical_pipe__Sex             0.190806
categorical_pipe__Title           0.158494
categorical_pipe__Cabin_1p        0.060253
categorical_pipe__Pclass          0.053249
numerical_pipe_con__Fare          0.039439
numerical_pipe_dis__IsAlone       0.026861
numerical_pipe_dis__Parch         0.013049
numerical_pipe_dis__SibSp         0.001903
numerical_pipe_con__Age           0.000000
numerical_pipe_dis__FamilySize    0.000000
categorical_pipe__Embarked        0.000000
Name: mutual information, dtype: float64

In [11]:
corr

,numerical_pipe_con__Age,numerical_pipe_con__Fare,numerical_pipe_dis__SibSp,numerical_pipe_dis__Parch,numerical_pipe_dis__IsAlone,numerical_pipe_dis__FamilySize
numerical_pipe_con__Age,1.000000,-0.025112,-0.335708,-0.337580,0.345122,-0.303624
numerical_pipe_con__Fare,-0.025112,1.000000,0.291299,0.303224,-0.428585,0.178895
numerical_pipe_dis__SibSp,-0.335708,0.291299,1.000000,0.440355,-0.579563,0.751619
numerical_pipe_dis__Parch,-0.337580,0.303224,0.440355,1.000000,-0.590175,0.576940
numerical_pipe_dis__IsAlone,0.345122,-0.428585,-0.579563,-0.590175,1.000000,-0.300387
numerical_pipe_dis__FamilySize,-0.303624,0.178895,0.751619,0.576940,-0.300387,1.000000