In [1]:
import os
import sys
import yaml
import pandas as pd
import seaborn as sns
current_dir = os.path.dirname(os.path.abspath('.'))
project_root = os.path.abspath(os.path.join(current_dir, "../.."))
sys.path.insert(0, project_root)
from utils.plots import Pearson_correlation, Bar_plot, plot_numerical_data
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [2]:
with open(os.path.join("../config/config.yaml"), "r") as f:
    config = yaml.safe_load(f)
        
with open(os.path.join( "../config/pipeline.yaml"), "r") as f:
    config_pipe = yaml.safe_load(f)

In [3]:
config['data']['processed']

'data/processed'

In [4]:
X_train = pd.read_parquet(
        os.path.join(
            config['init_path'],
            config['data']['feature_eng'],
            "X_train_feat_eng_pipeline1.parquet")
    )
y_train =  pd.read_parquet(
        os.path.join(
            config['init_path'],
            config['data']['feature_eng'],
            "y_train_feat_eng_pipeline1.parquet"))

In [5]:
X_train

,num_con_1_pipe__LotArea,num_con_1_pipe__TotalBsmtSF,num_con_1_pipe__GrLivArea,num_con_2_pipe__MasVnrArea,num_con_2_pipe__BsmtFinSF1,num_con_2_pipe__2ndFlrSF,num_con_2_pipe__WoodDeckSF,num_con_2_pipe__OpenPorchSF,num_con_2_pipe__GarageArea,num_con_2_pipe__BsmtUnfSF,...,categorical_pipe__ExterQual,categorical_pipe__Foundation,categorical_pipe__BsmtQual,categorical_pipe__BsmtCond,categorical_pipe__BsmtExposure,categorical_pipe__CentralAir,categorical_pipe__KitchenQual,categorical_pipe__GarageFinish,categorical_pipe__SaleType,categorical_pipe__SaleCondition
254,9.035987,7.181592,7.180831,0,7,0,8,0,7,7,...,TA,CBlock,TA,TA,No,Y,TA,RFn,WD,Normal
1066,8.966611,6.684612,7.359468,0,0,8,0,5,8,8,...,Gd,PConc,Gd,TA,No,Y,TA,RFn,WD,Normal
638,9.079890,6.680855,6.679599,0,0,0,8,0,0,8,...,TA,CBlock,Rare,TA,No,Y,TA,Rare,WD,Normal
799,8.881836,6.595781,7.477604,7,7,8,0,0,7,6,...,TA,Rare,Gd,TA,No,Y,Gd,Unf,WD,Normal
380,8.517193,6.934397,7.433075,0,6,8,0,0,7,8,...,TA,Rare,TA,TA,No,Y,Gd,Unf,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1095,9.139596,7.181592,7.180831,0,3,0,0,4,8,9,...,Gd,PConc,Gd,TA,No,Y,Gd,RFn,WD,Normal
1130,8.962392,7.023759,7.591357,0,7,8,8,6,8,8,...,TA,Rare,TA,TA,No,Y,Gd,Unf,WD,Normal
1294,9.008469,6.762730,6.761573,0,5,0,0,0,8,8,...,TA,CBlock,TA,TA,No,Y,TA,Unf,WD,Normal
860,8.941415,6.816736,7.262629,0,0,8,0,8,7,8,...,Gd,Rare,TA,TA,No,Y,Gd,Unf,WD,Normal
1126,8.211754,7.225481,7.349231,6,0,0,7,4,8,9,...,Gd,PConc,Gd,TA,No,Y,Gd,Fin,WD,Normal

In [11]:
y_train

      SalePrice
254      145000
1066     178000
638       85000
799      175000
380      127000
...         ...
1095     176432
1130     135000
1294     115000
860      189950
1126     174000

[1168 rows x 1 columns]